export const categoriesList = [
    { name: "Взуття", canBeDeleted: false },
    { name: "Дача, город, сад", canBeDeleted: false },
    { name: "Домашні улюбленці", canBeDeleted: false },
    { name: "Ігри, іграшки", canBeDeleted: false },
    { name: "Інструменти та автотехніка", canBeDeleted: false },
    { name: "Канцелярія", canBeDeleted: false },
    { name: "Косметика", canBeDeleted: false },
    { name: "Меблі", canBeDeleted: false },
    { name: "Медицина", canBeDeleted: false },
    { name: "Напої та продукти", canBeDeleted: false },
    { name: "Одяг", canBeDeleted: false },
    { name: "Особиста гігієна", canBeDeleted: false },
    { name: "Побутова хімія", canBeDeleted: false },
    { name: "Ремонт", canBeDeleted: false },
    { name: "Розваги", canBeDeleted: false },
    { name: "Сантехніка", canBeDeleted: false },
    { name: "Техніка та електроніка", canBeDeleted: false },
    { name: "Товари для дому", canBeDeleted: false },
    { name: "Флористика", canBeDeleted: false },
    { name: "Ювелірні вироби", canBeDeleted: false },
]
